xire -- Turn Vim script into a programmable programming language
================================================================
Kana Natsuno <kana@whileimautomaton.n3t>
:toc:





Introduction
------------

Xire is a tool to compile a domain-specific language into Vim script,
and xire is also the name of the DSL itself.  The DSL is based on Scheme
which is a dialect of Lisp.  Xire turns Vim script into a programmable
programming language.

One might wonder about reasons to use xire.  There are the following
problems about Vim script:

- Vim script is weak.  Because it is not designed as a programming
  language at the first.  Vim script is just a series of Ex commands,
  and its syntax is too arbitrary as a programming language.  Vim script
  is nearly impossible to extend the language itself, because the ways
  to abstract details are limited.
- There are several interfaces to other languages.  For example, Vim
  version 7.3 provides interfaces to Lua, Perl, Python, Ruby, Scheme and
  Tcl.  But the foreign language interfaces are not portable and they
  are not seamlessly integrated with Vim.

And all of the above problems can be resolved with xire.




Requirements
~~~~~~~~~~~~

- http://www.vim.org/[Vim] version 7.3 or later
- http://practical-scheme.net/gauche/[Gauche] version 0.9 or later




Links
~~~~~

- http://github.com/kana/vim-xire[Public source code repository]





External Commands
-----------------

xirec
~~~~~

A compiler that compile a xire script into Vim script.  It reads a xire
script from the standard input, then it writes the resulting Vim script
to the standard output.

.Typical Usage
----
$ xirec <foo.xire >foo.vim
----





Xire Script
-----------

Abstract
~~~~~~~~

Xire script is a Scheme-based DSL to write Vim script.  Xire script
consists of a series of xire expressions.  Xire expressions are
evaluated sequentially from first to last.

Each xire expression is a list of S expressions.  The first value of the
list is used to determine the type of the expression.  Each xire
expression can be classified into one of the following categories:

Directives::
    Directives control the current compiling process.  For example,
    a directive defines a new macro, while another directive Scheme
    environment to compile the current script.

Macros::
    Macros are corresponding to pieces of Vim script.  There are two
    types of statements.  One is a *statement macro* which is expanded
    into a series of Ex commands, and the other is an *expression macro*
    which is expanded into an expression of Vim script.  Macros can be
    nested.  Such macros are recursively expanded.




Process of Macro Expansion
~~~~~~~~~~~~~~~~~~~~~~~~~~

==== Low-Level Macros

Suppose that there is a following expression macro `foo`:

----
(define-xire-expr :low foo
  [pattern1 body1 ...]
  [pattern2 body2 ...]
  ...)
----

The process to expand a use of an expression macro `(foo bar baz)` is
roughly equivalent to the following code:

----
(use util.match)
(match '(bar baz)
  [pattern1 body1 ...]
  [pattern2 body2 ...]
  ...)
----

This process is also used to expand a use of statement macros.



==== High-Level Macros

Suppose that there is a following macro `foo`:

----
(define-xire-expr :high foo
  rule1
  rule2
  ...)
----

This definition is roughly equivalent to the following:

----
(eval
  `(define-xire-expr :low foo
    ,(match-clause-from-rule 'rule1)
    ,(match-clause-from-rule 'rule2)
    ...)
  (current-module))
----



==== High-Level Macro Rules

Low-level macros are defined with patterns and list processing code,
while high-level macros are defined with *rules*.  Each rule is
translated into a code (more precisely, a clause for
http://practical-scheme.net/gauche/man/?l=en&p=match[`match`]) to
generate <<_intermediate_format,intermediate format>>.


===== Interpretation of Rules

A use of high-level macro (the form) is matched against each rule,
from first one to last one.

If a matching rule is found, the form is expanded by the rule,
then this form returns the expanded form.

Otherwise, it is an error.


===== Format of Rules

The details of `rule` are as follows:

* `rule` is a list of S expressions.
** Examples: `(break)`, `(return $expr)`, `(if $cond:expr $then:stmt)`
* In `rule`, a symbol which name starts with `$` is called a *slot*.
* Slots are symbols.  The format of slot symbols is `$<name>:<type>`,
  where `<name>` is the name of a slot and `<type>` is the type of
  a resulting value.
** Examples: `$cond:expr`, `$then:stmt`
* Slot symbols may be written like `$<type>`.  This is a shorthand for
  `$<type>:<type>`.
** Examples: `$expr`, `$stmt`


===== Rules as Patterns

A use of high-level macro is matched against rules as patterns.
Details of matching process are as follows:

* Non-slot values in a rule match the same objects in a sense of `equal?`.
** Example: Rule `(break)` matches only `(break)`.
* Slot values in a rule are treated as pattern variables.
  They match arbitrary objects.
** Example: Rule `(return $expr)` matches `(return 1)`, `(return (list))`, etc.
* As a special case, the last value in a rule may be `...` (the symbol
  spelled with three periods).  The symbol `...` matches as if it is the
  value just before the symbol `...`.
** Example: Rule `(echo $expr ...)` matches `(echo 1)`, `(echo 1 2)`, etc.


===== Rules as Transformer

If a use of high-level macro (the form) matches a rule,
the form is transformed into a new list.

* Values in the form which match non-slot values in a rule
  are copied into the new list as is.
* Values in the form which match slot values in a rule
  are <<__transform_value,transformed into some values based on slot types>>,
  then the transformed values are inserted into the new list
  instead of values in the form.

For example, if a use of macro `(return (+ 1 1))` matches a rule
`(return $result:expr)`, transforming process of this form is roughly
equivalent to the following:

----
(use util.match)
(match '(return (+ 1 1))
  [('return $result:expr)
   (let ([$result (transform-value $result:expr 'expr)])
     `(return ,$result))])
----




Intermediate Format
~~~~~~~~~~~~~~~~~~~

Xire macros are finally expanded into corresponding code in Vim script.
However, results of macro expansion are accumulated and resulting Vim
script is not generated until the whole of a xire script is processed.

Results of macro expansion must be the intermediate format of Vim
script.  The details of the intermediate format are as follows:

`<boolean>` objects::
    Compiled into a corresponding boolean value in Vim script.

`<number>` objects::
    Compiled into a corresponding number value in Vim script.  Only
    exact integers are valid.  It is an error to use inexact numbers and
    non-integer numbers such as real numbers, though real numbers should
    be supported later.  Note that numbers in Vim script are limited in
    a range, and the range depends on how Vim executable is compiled.
    So that xire does not check whether a given number is also valid as
    Vim script or not.

`<regexp>` objects::
    Compiled into a corresponding string value in Vim script (because
    there is no literal notation for regular expressions in Vim script).

`<string>` objects::
    Compiled into a corresponding string value in Vim script.  See also
    <<_conventions_of_string_values, conventions of string values>>.

`<symbol>` objects::
    The names of symbols are normalized, then
    <<_normalization_of_variable_names,normalized names>> are embedded
    into resulting Vim script.

`(macro-name . args)`::
    `macro-name` is an arbitrary symbol and `args` is a list of
    arbitrary values.  If a xire macro which name is equal to
    `macro-name` is defined, the macro is expanded with `args`.
    Otherwise, it is an error.

`(x . xs)`::
    `x` is an arbitrary value except symbols.  This form is to embed
    arbitrary values into resulting Vim script.  Each value in this form
    is embedded with
    http://practical-scheme.net/gauche/man/?l=en&p=display[`display`],
    from left to right.



==== Conventions of String Values

The syntax of string literals is different between Scheme and Vim
script.  So that there are the following limitations on Scheme strings
which are compiled into Vim script:


===== Available Backslash-Escape Notations in Scheme Strings

In Scheme strings, only the following backslash-escape notations may be
used:

- `\\`
- `\"`
- `\f`
- `\n`
- `\r`
- `\t`
- `\uNNNN`
- `\xNN`
- `\<whitespace>*<newline><whitespace>*`

All but the last notation are also available in Vim script.  The last
notation is not available in Vim script, but it is processed and simply
discarded by ++read++er of Scheme.

So that external representation of Scheme strings and ones of Vim script
strings are the same if the above condition is met.  Therefore it's
possible to write Scheme strings as if they are Vim script strings.

Other notations (`\0` and `\UNNNNNNNN`) must not be used.  Because:

- There is no equivalent for `\UNNNNNNNN` in Vim script.
- Vim script cannot handle NUL character as is.  Though we can write
  `"\0"` in Vim script, such strings are essentially wrong.  So that it
  must not be used.


===== Unavailable Backslash-Escape Notations in Vim script Strings

The following backslash-escape notations in Vim script are not available
in xire script:

[options='header']
|===================================================================
|Label  |Notations              |Meaning
|(o)    |`\.`, `\..`, `\...`	|Arbitrary byte, in octal digits
|(x)    |`\x.`                  |Arbitrary byte, in single hex digit
|(X)    |`\X.`, `\X..`          |Equivalent to `\x.` and `\x..`
|(U)    |`\U....`               |Equivalent to `\u....`
|(b)    |`\b`                   |Equivalent to `\<BS>`
|(e)    |`\e`                   |Equivalent to `\<Esc>`
|(k)    |`\<Key>`               |Special key sequence
|===================================================================

- (o), (x) and (X): Use `"\xNN"` instead.
- (b) and (e): Use `"\xNN"` instead.
- (U): Incompatible with `"\UNNNNNNNN"` notation in Gauche strings and
  it is rarely used.
- (k): Use +(<<_kbd,kbd>> "<Key> ...")+ form instead.



==== Normalization of Variable Names

While various characters such as `$`, `!` and `%` can be used as
variable names in Scheme, variable names in Vim script must match to
`#/^[A-Za-z_][A-Za-z_0-9]*$/`.  So that it is generally an error to use
such characters for symbols in the <<_intermediate_format,intermediate
format>>.

But, for convenience, several characters (more precisely, patterns) can
be used for symbols in the intermediate format.

[options='header']
|==================================================================
|Pattern        |Replacement    |Example Symbol |Replacement Result
|`#/\?$/`       |`_p`           |`eq?`          |`eq_p`
|`#/!$/`        |`_x`           |`set!`         |`set_x`
|`#/->/`        |`_to_`         |`vector->list` |`vector_to_list`
|`#/[-%]/`      |`_`            |`read-char`    |`read_char`
|==================================================================




Directives
~~~~~~~~~~

==== `(define-xire-expr [mode] [context] name clause ...)`

`define-xire-expr` directive defines a new expression macro.

`mode` (`:high` or `:low`)::
    Specifies the mode which determines how the new macro is expanded.
    If `mode` is omitted, `:high` is used.

`context` (arbitrary symbol)::
    Specifies the name of a variable which is bound to the current
    context of a macro expansion.  This variable is available in
    ++body++s of each `clause`.  It may be omitted if `context` is
     not used in each `clause`.

`name` (arbitrary symbol)::
    Specifies the name of the new macro.

`clause` (`[pattern body ...]`, `[pattern (=> id) body ...]` or `rule`)::
    Specifies an expansion rule for the new macro.
    The first two formats of `clause` are available only for low-level
    macros, and the formats are the same as
    http://practical-scheme.net/gauche/man/?l=en&p=match[`match`].
    The third format is available only for high-level macros;
    see also <<__translate_rule,`translate-rule`>> for details.

See also <<_process_of_macro_expansion,Process of Macro Expansion>>.



==== `(define-xire-stmt [mode] [context] name clause ...)`

`define-xire-stmt` directive defines a new statement macro.

`mode` (`:high` or `:low`)::
    Specifies the mode which determines how the new macro is expanded.
    If `mode` is omitted, `:high` is used.

`context` (arbitrary symbol)::
    Specifies the name of a variable which is bound to the current
    context of a macro expansion.  This variable is available in
    ++body++s of each `clause`.  It may be omitted if `context` is
     not used in each `clause`.

`name` (arbitrary symbol)::
    Specifies the name of the new macro.

`clause` (`[pattern body ...]`, `[pattern (=> id) body ...]` or `rule`)::
    Specifies an expansion rule for the new macro.
    The first two formats of `clause` are available only for low-level
    macros, and the formats are the same as
    http://practical-scheme.net/gauche/man/?l=en&p=match[`match`].
    The third format is available only for high-level macros;
    see also <<__translate_rule,`translate-rule`>> for details.

See also <<_process_of_macro_expansion,Process of Macro Expansion>>.

There are also the following shorthands for `define-xire-stmt`:

`(define-xire-stmt <name>)`::
    Roughly equivalent to the following:

    (define-xire-stmt <name> "<name>")

`(define-xire-stmt <name> :!)`::
    Roughly equivalent to the following:

    (define-xire-stmt <name> "<name>")
    (define-xire-stmt <name> "<name>!")

`(define-xire-stmt <name> <ex-command-name>)`::
    Roughly equivalent to the following:

    (define-xire-stmt <name>
      [(_)
       '(<ex-command-name>)])  ; <ex-command-name> must be a string.



==== `(scheme scheme-expression ...)`

`scheme` directive evaluates arbitrary ++scheme-expression++s as if
`(begin scheme-expression ...)`.




Helper API
~~~~~~~~~~

In xire script, the following API is available to define xire macros:



[[__match_body_from_rule]]
==== `(match-body-from-rule rule)`

A function which translates `rule` into a body of clause for
http://practical-scheme.net/gauche/man/?l=en&p=match[`match`].

For example,

----
(match-body-from-rule '(if $cond:expr $then:stmt))
----

is roughly equivalent to the following:

----
`(let ([$cond (transform-value $cond:expr 'expr)]
       [$then (transform-value $then:stmt 'stmt)])
   (lines
     ("if" $cond)
     $then
     ("endif")))
----

See also <<_high_level_macro_rules,high-level macro rules>>.



[[__match_clause_from_rule]]
==== `(match-clause-from-rule rule)`

A function which translates `rule` into a clause for
http://practical-scheme.net/gauche/man/?l=en&p=match[`match`].

For example,

----
(match-clause-from-rule '(if $cond:expr $then:stmt))
----

is roughly equivalent to the following:

----
`(,(match-pattern-from-rule '(if $cond:expr $then:stmt))
  ,(match-body-from-rule '(if $cond:expr $then:stmt)))
----

See also:

* <<__match_body_from_rule,`match-body-from-rule`>>
* <<__match_pattern_from_rule,`match-pattern-from-rule`>>



[[__match_pattern_from_rule]]
==== `(match-pattern-from-rule rule)`

A function which translates `rule` into a pattern of clause for
http://practical-scheme.net/gauche/man/?l=en&p=match[`match`].

For example,

----
(match-pattern-from-rule '(if $cond:expr $then:stmt))
----

is roughly equivalent to the following:

----
`('if $cond:expr $then:stmt)
----

See also <<_high_level_macro_rules,high-level macro rules>>.




Macros
~~~~~~

FIXME: Write about details of macros.





License
-------

So-called MIT/X license.

Copyright (C) 2009-2011 Kana Natsuno <kana@whileimautomaton.n3t>

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.





// vim: filetype=asciidoc
// vim: textwidth=72 expandtab softtabstop=4 shiftwidth=4
